// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Reuse the app's loader rather than "dotenv/config": that only reads .env, and
// this project keeps its secrets in .env.local, so datasource.url came back
// undefined and every CLI command needing the database failed.
import "./loadEnv.ts";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"]!,
  },
});
